namespace Raptor21.EF.Extensions.StoredProcedures.Generator;

/// <summary>The attribute source injected into the consumer compilation via post-initialization output.</summary>
internal static class EmittedAttributes
{
    public const string Namespace = "Raptor21.EF.Extensions.StoredProcedures.Generated";
    public const string GroupAttributeMetadataName = Namespace + ".StoredProcedureGroupAttribute";
    public const string ProcedureAttributeMetadataName = Namespace + ".StoredProcedureAttribute";
    public const string SqlAttributeMetadataName = Namespace + ".SqlAttribute";
    public const string RowAttributeMetadataName = Namespace + ".SqlRowAttribute";
    public const string ColumnAttributeMetadataName = Namespace + ".SqlColumnAttribute";

    public const string Source = """
        // <auto-generated/>
        #nullable enable
        namespace Raptor21.EF.Extensions.StoredProcedures.Generated
        {
            /// <summary>Marks a partial class as a stored-procedure group. The generator emits its constructor and method bodies.</summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
            [global::System.CodeDom.Compiler.GeneratedCode("Raptor21.EF.Extensions.StoredProcedures.Generator", null)]
            internal sealed class StoredProcedureGroupAttribute : global::System.Attribute
            {
            }

            /// <summary>Marks a partial method as a stored-procedure call. Argument is the proc name (e.g. "dbo.ACCOUNT_LOGIN").</summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
            [global::System.CodeDom.Compiler.GeneratedCode("Raptor21.EF.Extensions.StoredProcedures.Generator", null)]
            internal sealed class StoredProcedureAttribute : global::System.Attribute
            {
                public StoredProcedureAttribute(string fullName) { FullName = fullName; }
                public string FullName { get; }
            }

            /// <summary>Declares the SQL parameter name (mandatory, 1st arg) and optional SQL type/length/precision/scale for a parameter.</summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Parameter, AllowMultiple = false, Inherited = false)]
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
            [global::System.CodeDom.Compiler.GeneratedCode("Raptor21.EF.Extensions.StoredProcedures.Generator", null)]
            internal sealed class SqlAttribute : global::System.Attribute
            {
                public SqlAttribute(string name) { Name = name; }
                public SqlAttribute(string name, int length) { Name = name; Length = length; }
                public SqlAttribute(string name, string typeName) { Name = name; TypeName = typeName; }
                public SqlAttribute(string name, string typeName, int length) { Name = name; TypeName = typeName; Length = length; }

                /// <summary>SQL parameter name, e.g. "@AccountID". Mandatory.</summary>
                public string Name { get; }
                /// <summary>Explicit SQL type name override (e.g. "nvarchar"). When null, inferred from the .NET type.</summary>
                public string? TypeName { get; }
                /// <summary>Max length for string/binary types. -1 = unspecified.</summary>
                public int Length { get; } = -1;
                /// <summary>Decimal precision.</summary>
                public byte Precision { get; set; }
                /// <summary>Decimal scale.</summary>
                public byte Scale { get; set; }
                /// <summary>True for OUTPUT parameters (Faz 3).</summary>
                public bool Output { get; set; }
            }

            /// <summary>Marks a partial positional record as a stored-procedure result row. The generator emits FromDataRecord.</summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
            [global::System.CodeDom.Compiler.GeneratedCode("Raptor21.EF.Extensions.StoredProcedures.Generator", null)]
            internal sealed class SqlRowAttribute : global::System.Attribute
            {
            }

            /// <summary>Overrides the SQL result-set column name a row member maps to (defaults to the member name).</summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Parameter | global::System.AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
            [global::System.CodeDom.Compiler.GeneratedCode("Raptor21.EF.Extensions.StoredProcedures.Generator", null)]
            internal sealed class SqlColumnAttribute : global::System.Attribute
            {
                public SqlColumnAttribute(string name) { Name = name; }
                public string Name { get; }
            }
        }
        """;
}
