// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Raptor21.EF.Extensions.Sample.Data;

#nullable disable

namespace Raptor21.EF.Extensions.Sample.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260830014500_AddProductListView")]
    partial class AddProductListView
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("Sp:dbo.Product_GetBySku", "CREATE OR ALTER PROCEDURE dbo.Product_GetBySku\n    @Sku varchar(32)\nAS\nBEGIN\n    SET NOCOUNT ON;\n\n    SELECT Id, Sku, Name, Price, UpdatedUtc\n      FROM dbo.Product\n     WHERE Sku = @Sku;\nEND\n")
                .HasAnnotation("Sp:dbo.Product_List", "CREATE OR ALTER PROCEDURE dbo.Product_List\n    @Take int\nAS\nBEGIN\n    SET NOCOUNT ON;\n\n    SELECT TOP (@Take) Id, Sku, Name, Price, UpdatedUtc\n      FROM dbo.Product\n     ORDER BY Id;\n\n    DECLARE @Total int = (SELECT COUNT(*) FROM dbo.Product);\n    RETURN @Total;\nEND\n")
                .HasAnnotation("Sp:dbo.Product_ListView", "CREATE OR ALTER PROCEDURE dbo.Product_ListView\n    @Take int\nAS\nBEGIN\n    SET NOCOUNT ON;\n\n    -- The column order below is the MODEL's, not this file's choice. ProductListRow's members are\n    -- generated in snapshot order - primary key first, then alphabetical; ProductListResult is keyless,\n    -- so plain alphabetical - and StoredProcedureValidator compares result columns POSITIONALLY while\n    -- the generated reader looks them up BY NAME. Reorder this SELECT to read more naturally and the\n    -- app fails at startup with a result-column name mismatch, not with a wrong value.\n    --\n    -- One thing no model can check: the server reports the nullability of the EXPRESSION, not of the\n    -- column. Wrap a column in ISNULL, or reach it through an outer join or a UNION, and a NOT NULL\n    -- column arrives nullable. That one stays the procedure author's to keep.\n    SELECT TOP (@Take)\n           p.Id,\n           p.Name,\n           p.Price,\n           p.Sku\n      FROM dbo.Product AS p\n     ORDER BY p.Id;\nEND\n")
                .HasAnnotation("Sp:dbo.Product_TouchStamp", "CREATE OR ALTER PROCEDURE dbo.Product_TouchStamp\n    @Id int\nAS\nBEGIN\n    SET NOCOUNT ON;\n\n    UPDATE dbo.Product\n       SET UpdatedUtc = GETUTCDATE()\n     WHERE Id = @Id;\nEND\n")
                .HasAnnotation("Sp:dbo.Product_Upsert", "CREATE OR ALTER PROCEDURE dbo.Product_Upsert\n    @Sku   varchar(32),\n    @Name  varchar(128),\n    @Price decimal(18,2),\n    @Id    int OUTPUT\nAS\nBEGIN\n    SET NOCOUNT ON;\n\n    UPDATE dbo.Product\n       SET Name = @Name, Price = @Price, UpdatedUtc = GETUTCDATE(), @Id = Id\n     WHERE Sku = @Sku;\n\n    IF @@ROWCOUNT = 0\n    BEGIN\n        INSERT INTO dbo.Product (Sku, Name, Price, UpdatedUtc)\n        VALUES (@Sku, @Name, @Price, GETUTCDATE());\n\n        SET @Id = CAST(SCOPE_IDENTITY() AS int);\n        RETURN 1;   -- inserted\n    END\n\n    RETURN 0;       -- updated\nEND\n");

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Raptor21.EF.Extensions.Sample.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("Raptor21.EF.Extensions.Sample.Data.ProductListResult", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.ToTable((string)null);

                    b.ToView("vw_ProductList", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
