// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Raptor21.EF.Extensions.Sample.Data;

#nullable disable

namespace Raptor21.EF.Extensions.Sample.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260830001443_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("Sp:dbo.Product_GetBySku", "CREATE OR ALTER PROCEDURE dbo.Product_GetBySku\n    @Sku varchar(32)\nAS\nBEGIN\n    SET NOCOUNT ON;\n\n    SELECT Id, Sku, Name, Price, UpdatedUtc\n      FROM dbo.Product\n     WHERE Sku = @Sku;\nEND\n")
                .HasAnnotation("Sp:dbo.Product_List", "CREATE OR ALTER PROCEDURE dbo.Product_List\n    @Take int\nAS\nBEGIN\n    SET NOCOUNT ON;\n\n    SELECT TOP (@Take) Id, Sku, Name, Price, UpdatedUtc\n      FROM dbo.Product\n     ORDER BY Id;\n\n    DECLARE @Total int = (SELECT COUNT(*) FROM dbo.Product);\n    RETURN @Total;\nEND\n")
                .HasAnnotation("Sp:dbo.Product_TouchStamp", "CREATE OR ALTER PROCEDURE dbo.Product_TouchStamp\n    @Id int\nAS\nBEGIN\n    SET NOCOUNT ON;\n\n    UPDATE dbo.Product\n       SET UpdatedUtc = GETUTCDATE()\n     WHERE Id = @Id;\nEND\n")
                .HasAnnotation("Sp:dbo.Product_Upsert", "CREATE OR ALTER PROCEDURE dbo.Product_Upsert\n    @Sku   varchar(32),\n    @Name  varchar(128),\n    @Price decimal(18,2),\n    @Id    int OUTPUT\nAS\nBEGIN\n    SET NOCOUNT ON;\n\n    UPDATE dbo.Product\n       SET Name = @Name, Price = @Price, UpdatedUtc = GETUTCDATE(), @Id = Id\n     WHERE Sku = @Sku;\n\n    IF @@ROWCOUNT = 0\n    BEGIN\n        INSERT INTO dbo.Product (Sku, Name, Price, UpdatedUtc)\n        VALUES (@Sku, @Name, @Price, GETUTCDATE());\n\n        SET @Id = CAST(SCOPE_IDENTITY() AS int);\n        RETURN 1;   -- inserted\n    END\n\n    RETURN 0;       -- updated\nEND\n");

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Raptor21.EF.Extensions.Sample.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("Product", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
